let str1='Hello World';
let str2='Ust Global Company';
let str3='Maneesha';
let str4='Beautiful House';
let str5='Keep Smile';
let str6='Life is Beautiful';
let str7='Java Script';
let str8='Mobiles ';
let str9='Love Yourself';
let str10='Karthik';
console.log('Upper Case');
str=str1.toUpperCase();
console.log(str);
str=str2.toUpperCase();
console.log(str);
str=str3.toUpperCase();
console.log(str);
str=str4.toUpperCase();
console.log(str);
str=str5.toUpperCase();
console.log(str);
str=str6.toUpperCase();
console.log(str);
str=str7.toUpperCase();
console.log(str);
str=str8.toUpperCase();
console.log(str);
str=str9.toUpperCase();
console.log(str);
str=str10.toUpperCase();
console.log(str);
console.log('-------------------------------');
console.log('Lower Case')
str=str1.toLowerCase();
console.log(str);
str=str2.toLowerCase();
console.log(str);
str=str3.toLowerCase();
console.log(str);
str=str4.toLowerCase();
console.log(str);
str=str5.toLowerCase();
console.log(str);
str=str6.toLowerCase();
console.log(str);
str=str7.toLowerCase();
console.log(str);
str=str8.toLowerCase();
console.log(str);
str=str9.toLowerCase();
console.log(str);
str=str10.toLowerCase();
console.log(str);
console.log('--------------------------------');
console.log('Char At Method');
str=str1.charAt(4);
console.log(str);
str=str2.charAt(4);
console.log(str);
str=str3.charAt(4);
console.log(str);
str=str4.charAt(4);
console.log(str);
str=str5.charAt(2);
console.log(str);
str=str6.charAt(1);
console.log(str);
str=str7.charAt(3);
console.log(str);
str=str8.charAt(5);
console.log(str);
str=str9.charAt(7);
console.log(str);
str=str10.charAt(4);
console.log(str);
console.log('--------------------------------');
console.log('Index Of Method');
str=str1.indexOf('ld',2);
console.log(str);
str=str2.indexOf('ba',4);
console.log(str);
str=str3.indexOf('sh',2);
console.log(str);
str=str4.indexOf('ti',2);
console.log(str);
str=str5.indexOf('ee',2);
console.log(str);
str=str6.indexOf('is',2);
console.log(str);
str=str7.indexOf('ri',2);
console.log(str);
str=str8.indexOf('bi',2);
console.log(str);
str=str9.indexOf('se',2);
console.log(str);
str=str10.indexOf('ar',2);
console.log('--------------------------------');
console.log('Replace Method');
str=str1.replace("llo","oool");
console.log(str);
str=str2.replace("Ust","oool");
console.log(str);
str=str3.replace("Ma","oool");
console.log(str);
str=str4.replace("Be","oool");
console.log(str);
str=str5.replace("ep","oool");
console.log(str);
str=str6.replace("is","oool");
console.log(str);
str=str7.replace("ri","oool");
console.log(str);
str=str8.replace("bi","oool");
console.log(str);
str=str9.replace("se","oool");
console.log(str);
str=str10.replace("ik","oool");
console.log(str);
console.log('--------------------------------');
console.log('Concat Method');
str=str1.concat(' Hello Hello World');
console.log(str);
str=str2.concat(' Hii');
console.log(str);
str=str3.concat(' Vangimalla');
console.log(str);
str=str4.concat(' In');
console.log(str);
str=str5.concat(' Hello ');
console.log(str);
str=str6.concat(' Hiii');
console.log(str);
str=str7.concat(' Good Morning');
console.log(str);
str=str8.concat(' Hello ');
console.log(str);
str=str9.concat(' Hiii');
console.log(str);
str=str10.concat(' Hello');
console.log(str);
console.log('---------------------------------------');
console.log('Includes Method');
str=str1.includes('ll',2);
console.log(str);
str=str2.includes('st',2);
console.log(str);
str=str3.includes('ee',2);
console.log(str);
str=str4.includes('fu',2);
console.log(str);
str=str5.includes('ep',2);
console.log(str);
str=str6.includes('ab',2);
console.log(str);
str=str7.includes('ll',2);
console.log(str);
str=str8.includes('ll',2);
console.log(str);
str=str9.includes('ll',2);
console.log(str);
str=str10.includes('ar',1);
console.log(str);
console.log('--------------------------------------');
console.log('Search Method');
str=str1.search('ell');
console.log(str);
str=str2.search('ell');
console.log(str);
str=str3.search('st');
console.log(str);
str=str4.search('ee');
console.log(str);
str=str5.search('mi');
console.log(str);
str=str6.search('ea');
console.log(str);
str=str7.search('va');
console.log(str);
str=str8.search('bi');
console.log(str);
str=str9.search('ou');
console.log(str);
str=str10.search('ar');
console.log(str);
console.log('----------------------------------------');
console.log('Split Method');
str=str1.split('o');
console.log(str);
str=str2.split('s');
console.log(str);
str=str3.split('e');
console.log(str);
str=str4.split('e');
console.log(str);
str=str5.split('i');
console.log(str);
str=str6.split('s');
console.log(str);
str=str7.split('a');
console.log(str);
str=str8.split('o');
console.log(str);
str=str9.split('o');
console.log(str);
str=str10.split('a');
console.log(str);
console.log('-----------------------------------');
console.log('Trim Method');
str=str1.trim();
console.log(str);
str=str2.trim();
console.log(str);
str=str3.trim();
str=str4.trim();
console.log(str);
str=str5.trim();
str=str6.trim();
console.log(str);
str=str7.trim();
console.log(str);
str=str8.trim();
console.log(str);
str=str9.trim();
console.log(str);
str=str10.trim();
console.log(str);
console.log('-----------------------------------------');
console.log('sub string method');
str=str1.substr(0,4);
console.log(str);
str=str2.substr(0,4);
console.log(str);
str=str3.substr(0,4);
console.log(str);
str=str4.substr(0,4);
console.log(str);
str=str5.substr(0,4);
console.log(str);
str=str6.substr(0,4);
console.log(str);
str=str7.substr(0,4);
console.log(str);
str=str8.substr(0,4);
console.log(str);
str=str9.substr(0,4);
console.log(str);
str=str10.substr(0,4);
console.log(str);
